server:
  port: 19872
  servlet:
    context-path: /ru.geekbrains.april.market
spring:
  application:
    name: products-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
eureka:
  client:
    serviceUrl: defaultZone=${EUREKA_URI:http://localhost:8761/eureka_products}
